[build] 
  publish = "dist"
  command = "npm run build"

[dev] 
  publish = "dist"
  command = "npm run dev"

[[redirects]]
  from = "/notes/"
  to = "/notes/1/"
  status = 301

[[redirects]]
  from = "/note/tw/*"
  to = "/.netlify/functions/note-tweet"
  status = 200
